#ifndef __GAME_ENTITIES_ENTITYSTATES_H_INCLUDED__
#define __GAME_ENTITIES_ENTITYSTATES_H_INCLUDED__

enum ENTITYSTATES
{
	ENTITYSTATE_NONE,
	ENTITYSTATE_IDLE,
	ENTITYSTATE_WALKING,
	ENTITYSTATE_FALLING,
	ENTITYSTATE_JUMPING,
	ENTITYSTATE_DEAD,
	ENTITYSTATE_PUNCHING,
	ENTITYSTATE_SHOOTING,
	ENTITYSTATE_OPEN,
	ENTITYSTATE_INACTIVE
};

#endif

